services:
  - type: web
    name: confession-wall-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5500
      - key: DATABASE
        value: ./data/campus_confessions.db